@startuml WOPI
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml
!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Databases/AzureCosmosDb.puml
!includeurl AzurePuml/Identity/AzureActiveDirectory.puml
!includeurl AzurePuml/Storage/AzureBlobStorage.puml
!includeurl AzurePuml/Web/AzureWebApp.puml
!includeurl AzurePuml/Security/AzureKeyVault.puml
!includeurl AzurePuml/DevOps/AzureApplicationInsights.puml
!includeurl AzurePuml/Networking/AzureTrafficManager.puml
!includeurl AzurePuml/Networking/AzureVPNGateway.puml
!includeurl AzurePuml/Networking/AzureVirtualNetwork.puml
!includeurl AzurePuml/Compute/AzureVirtualMachine.puml


frame "Azure Northern Europe" as azRgNe {
    frame "Hub-Env-NEU-RG" as azRgHuNe {
    Person( user, "Browser", "IFrame")
        AzureVirtualMachine( hubNe, "HUB", "Web Application")
        AzureVPNGateway( azVpnNe, "VPN Gateway", "Hub-Env-NEU-Common-VN-VNG")
        AzureBlobStorage( azBsNe, "File Storage RA-GRS", "kfhubenvneust01")
    }

    frame "RG Wopi Host" as azRgWhNe {
        AzureWebApp( azWaNe, "WOPI Host", "Provides Office Online access to the blob store")
    }
}

frame "Knight Frank" as azKf {
    Container(oos, "Office Online Server", "*.wopihost.hub.knightfrank.com")
}


hubNe <-up-> user : Interacts
user -up-> oos : Request File 
oos -down-> azWaNe : Read / Write
hubNe -down-> azBsNe : Writes

azWaNe -up-> azVpnNe : Discovery
azVpnNe -up-> oos : Discovery
azWaNe -down-> azBsNe : Get / Put

frame "Shared Components" as azRgSh {
    AzureCosmosDb( azDb, "DataStore", "")
    AzureActiveDirectory( azAd, "Authentication", "")
    AzureApplicationInsights( azAi, "Logs/Analysis", "")
}

azWaNe -right-> azRgSh


@enduml