@startuml WOPI
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml
!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Databases/AzureCosmosDb.puml
!includeurl AzurePuml/Identity/AzureActiveDirectory.puml
!includeurl AzurePuml/Storage/AzureBlobStorage.puml
!includeurl AzurePuml/Web/AzureWebApp.puml
!includeurl AzurePuml/Security/AzureKeyVault.puml
!includeurl AzurePuml/DevOps/AzureApplicationInsights.puml
!includeurl AzurePuml/Networking/AzureTrafficManager.puml
!includeurl AzurePuml/Networking/AzureVPNGateway.puml
!includeurl AzurePuml/Networking/AzureVirtualNetwork.puml


frame "Azure Northern Europe" as azRgNe {
    frame "RG Hub" as azRgHuNe {
        AzureBlobStorage( azBsNe, "File Storage", "RA-GRS")
        AzureVPNGateway( azVpnNe, "VPN Gateway", "")
        AzureWebApp( hubNe, "HUB", "Web Application")
    }
    frame "RG Wopi Host" as azRgWhNe {
        AzureWebApp( azWaNe, "WOPI Host", "Provides Office Online access to the blob store")
        AzureKeyVault( azKvNe, "Key Vault", "Secrets")
    }
}

frame "Azure Western Europe" as azRgWe {
    frame "RG Hub" as azRgHuWe {
        AzureWebApp( hubWe, "HUB", "Web Application")
        AzureVPNGateway( azVpnWe, "VPN Gateway", "")
        AzureBlobStorage( azBsWe, "File Storage Copy", "RA-GRS")
    }
    
    frame "RG Wopi Host" as azRgWhWe {
        AzureKeyVault( azKvWe, "Key Vault", "Secrets")
        AzureWebApp( azWaWe, "WOPI Host", "Provides Office Online access to the blob store")
    }
}

AzureTrafficManager( azTm, "Traffic Manager", "Traffic Manager")
Person( user, "Browser", "IFrame")
frame "Knight Frank" as azKf {
    Container(oos, "Office Online Server", "*.wopihost.hub.knightfrank.com")
}

azTm --> azWaNe
azTm --> azWaWe
user --> azTm : Read / Write
oos <-- user : Request File 

hubNe <-up-> user : Interacts
azVpnNe -up-> oos : Discovery

hubWe <-up-> user : Interacts
azVpnWe -up-> oos : Discovery

azWaWe -up-> azVpnWe : Discovery
azWaNe -up-> azVpnNe : Discovery

azWaNe -up-> azBsNe : Get / Put
azWaWe -up-> azBsNe : Get / Put

azWaNe .up.> azBsWe : Failover
azWaWe .up.> azBsWe : Failover

hubNe -right-> azBsNe : Writes
hubWe -left-> azBsNe : Writes

azBsNe ..> azBsWe : Copy

frame "Shared Components" as azRgSh {
    AzureCosmosDb( azDb, "DataStore", "")
    AzureActiveDirectory( azAd, "Authentication", "")
    AzureApplicationInsights( azAi, "Logs/Analysis", "")
	AzureKeyVault( azKv, "KeyVault", "Secrets")
}

azWaNe --> azRgSh
azWaWe --> azRgSh

@enduml
