@startuml WOPI
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml
!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/master/dist

Title Wopi Context Diagram

Container(spa, "Hub SPA Client", "AngularJs")
Container(hub, "Hub Server Api", "hub.knightfrank.com")
System_Ext(oos, "Office Online Server")
frame "Wopi Host" as wopihost {
    Container(whClientApi, "Wopi Client Api", "<env>wopihost.hub.knightfrank.com")
    Container(whOOSApi, "Wopi Office Online Api", "<env>wopihost.hub.knightfrank.com")

    whClientApi --> hub : Get FileInfo
    whClientApi -> oos : Get Discovery
    whOOSApi --> hub : Get/Post\nFile Contents
}

spa --> whClientApi : Get Office URL
oos --> whOOSApi : Get/Post\nFile Contents
spa -> oos : Iframe

@enduml