@startuml WOPI
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml
!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Databases/AzureCosmosDb.puml
!includeurl AzurePuml/Identity/AzureActiveDirectory.puml
!includeurl AzurePuml/Storage/AzureBlobStorage.puml
!includeurl AzurePuml/Web/AzureWebApp.puml
!includeurl AzurePuml/Security/AzureKeyVault.puml
!includeurl AzurePuml/DevOps/AzureApplicationInsights.puml
!includeurl AzurePuml/Networking/AzureTrafficManager.puml
!includeurl AzurePuml/Networking/AzureVPNGateway.puml
!includeurl AzurePuml/Networking/AzureVirtualNetwork.puml
!includeurl AzurePuml/Compute/AzureVirtualMachine.puml

actor user
frame "Hub Application" as hub {
    Container(hubSl, "File Selection", "")
    Container(hubIf, "Office IFrame ", "")
    AzureBlobStorage( azBsNe, "File Storage", "kfhubprodneust01")

    database hubdb

    hubSl -[hidden] hubdb
    hubdb -[hidden] azBsNe
    azBsNe -[hidden] hubIf
}

frame "Wopi RG" as wopi {
    AzureWebApp( azWhNe, "WOPI Api Client", "wopihost-webapp-dev-ne")
    AzureWebApp( azWaNe, "WOPI Api Server", "wopiapi-webapp-dev-ne")
}
frame "Knight Frank" as azKf {
    Container(oos, "Office Online Server", "*.wopihost.hub.knightfrank.com")
}

user -down-> hubSl 
hubSl -down-> azWhNe : 1, Request File

azWhNe -down-> oos : 2,Create AccessToken(User,FileId) and request file from OOS
oos -down-> azWaNe : 3,Get FileInfo, pass AccessToken

azWaNe --> azWaNe : 4, Validate AccessToken

azWaNe -down-> hubdb : 5,Get FileInfo( user, fileId)
hubdb -up-> azWaNe : 6,Returns FileInfo or Unauthorised
azWaNe -up-> oos : 7,11,Response

oos --> azWaNe : 8,Get File
azWaNe -down-> azBsNe : 9,Get File
azBsNe -up-> azWaNe : 10,Response File

oos --> hubIf : 12,Response
hubIf -down-> user 

@enduml