@startuml WOPI
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml
!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Databases/AzureCosmosDb.puml
!includeurl AzurePuml/Identity/AzureActiveDirectory.puml
!includeurl AzurePuml/Storage/AzureBlobStorage.puml
!includeurl AzurePuml/Web/AzureWebApp.puml
!includeurl AzurePuml/Security/AzureKeyVault.puml
!includeurl AzurePuml/DevOps/AzureApplicationInsights.puml
!includeurl AzurePuml/Networking/AzureTrafficManager.puml
!includeurl AzurePuml/Networking/AzureVPNGateway.puml
!includeurl AzurePuml/Networking/AzureVirtualNetwork.puml
!includeurl AzurePuml/Compute/AzureVirtualMachine.puml


Container(spa, "Hub SPA Client", "")
Container(hub, "Hub Api Server", "hub.knightfrank.com")
System_Ext(oos, "Office Online Server")
frame "Wopi Host" as wopihost {
    Container(whClientApi, "Hub Client Api", "<env>wopihost.hub.knightfrank.com")
    Container(whOOSApi, "Office Online Api", "<env>wopihost.hub.knightfrank.com")

    whClientApi --> hub : Get FileInfo
    whClientApi -> oos : Get Discovery
    whOOSApi --> hub : Get/Post\nFile Contents
}

spa --> whClientApi : Get Office URL
oos --> whOOSApi : Get/Post\nFile Contents
spa -> oos : Iframe

@enduml