@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

title Wopi System Component diagram 

Container(spa, "Single-Page App", "JavaScript, Angular", "Provides a list of available files\nIframe for viewing docuemnts")
ContainerDb(database, "Database", "SQL Database", "Stores attachment table, audit logs, etc.")
Container(backend_api, "API Application", "C# api", "Provides authorisation, file creation, and logging functions ")

Container_Boundary(wopapp, "Wopi Application") {
    Component(wopapi, "Hub Api Controller", "MVC Rest Controller", "Allows the HUB to request files")
    Component(oosapi, "OOS Api Controller", "MVC Rest Controller", "Allows the OOS to request files")
}
    
Container(filestore, "File Store", "Azure BlobStore", "Provides storage for generated documents")
System_Ext(oos, "Office Online Server", "internal Microsoft Office Server")

Rel(spa, backend_api, "Uses", "async, JSON/HTTPS")
'Rel(backend_api, filestore, "Uses", "async, JSON/HTTPS")
'Rel(backend_api, database, "Reads from and writes to", "sync, ODBC")
Rel_Neighbor(spa, wopapi, "Uses", "sync/async, JSON/HTTPS")

Rel(wopapi, database,"Reads file Info from", "sync, ODBC")
Rel(wopapi, oos, "Uses", "async, JSON/HTTPS")

Rel(oosapi, database,"Reads file from and writes locking and logging to", "sync, ODBC")
Rel(oosapi, filestore, "Reads/Writes files", "async, JSON/HTTPS")
Rel(oos, oosapi, "Uses", "async, JSON/HTTPS")

@enduml