@startuml WOPI
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml
!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Databases/AzureCosmosDb.puml
!includeurl AzurePuml/Identity/AzureActiveDirectory.puml
!includeurl AzurePuml/Storage/AzureBlobStorage.puml
!includeurl AzurePuml/Web/AzureWebApp.puml
!includeurl AzurePuml/Security/AzureKeyVault.puml
!includeurl AzurePuml/DevOps/AzureApplicationInsights.puml
!includeurl AzurePuml/Networking/AzureTrafficManager.puml
!includeurl AzurePuml/Networking/AzureVPNGateway.puml
!includeurl AzurePuml/Networking/AzureVirtualNetwork.puml
!includeurl AzurePuml/Compute/AzureVirtualMachine.puml

    AzureActiveDirectory( azAd, "Authentication", "azureteamknightfrank.onmicrosoft.com")


frame "Azure Northern Europe" as azRgNe {

    frame "RG Hub-Wopi-ENV-Neu-RG" as azRgWhNe {
        AzureWebApp( azWaNe, "Wopi Api", "wopihost-webapp-ENV-ne")
        AzureApplicationInsights( azAiNe, "Logs/Analysis", "wopihost-appins-dev-ne")
        AzureKeyVault( azKvNe, "KeyVault", "wopihost-kv-dev-ne")
    }
    
    AzureTrafficManager( azTm, "TrafficManager", "")
        
    frame "RG Hub-ENV-NEU-RG" as azRgAlNe {
        AzureVPNGateway( azVpnNe, "VPN Gateway", "Hub-Env-NEU-Common-VN-VNG")
        AzureWebApp( azWaHuNe, "Hub Api", "To be determined")
    }
}

frame "Knight Frank" as azKf {
    Container(oos, "Office Online Server", "*.wopihost.hub.knightfrank.com")
}

azWaNe --> oos  : Request File 
'user -up-> azWaNe : Request File 
oos -down-> azWaNe : Read / Write

azWaNe -up-> azVpnNe : Discovery
azVpnNe -up-> oos : Discovery

azWaNe -down-> azAd : Get
azWaNe -down-> azAiNe : Put
azWaNe -left-> azKvNe : Get

azWaHuNe -down-> azTm
azTm -down-> azWaNe
azTm -down-> WopiWE : Western Europe Wopi Instance


@enduml